name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  python_ci:
    name: Test and Lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.17

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run pytest
      run: pytest
      continue-on-error: true

    - name: Run flake8
      run:  flake8 --max-line-length 150

  deploy_to_render:
    name: CD to Render
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    needs: python_ci  # Wait for the 'Python CI' job to complete

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://render.com/v1/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"public": true, "branch": "${{ github.ref }}"}'
